package com.arushi.typeahead.trendingrankingservice.repository;

import com.arushi.typeahead.trendingrankingservice.model.SearchTerm;
import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SearchTermRepository extends MongoRepository<SearchTerm, String> {
    // This allows fetching top 10 suggestions based on the prefix.
    // Queries are automatically generated by Spring Data MongoDB.
    List<SearchTerm> findTop10ByOrderByFrequencyDesc();
    List<SearchTerm> findTop10ByTermStartingWithOrderByFrequencyDesc(String prefix);
    List<SearchTerm> findByTermStartingWith(String prefix);  // Add this method
}
